// Emits the bytecode program the reference PEG.js compiler produces for a
// grammar, as a MoonBit `@bytecode.Program` literal.
//
//   node tools/gen-program.js <grammar.pegjs> <binding-name> [options-json]
//
// Used to freeze the meta-grammar parser (parser/meta_program.mbt).
"use strict";
const fs = require("fs");
const path = require("path");
const { compileInternals } = require("./dump");

function hasLoneSurrogate(s) {
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    if (c >= 0xd800 && c <= 0xdbff) {
      const d = s.charCodeAt(i + 1);
      if (!(d >= 0xdc00 && d <= 0xdfff)) return true;
      i++;
    } else if (c >= 0xdc00 && c <= 0xdfff) return true;
  }
  return false;
}

// A MoonBit expression of type String equal to the JS string `s`.
function mbtString(s) {
  if (hasLoneSurrogate(s)) {
    const units = [];
    for (let i = 0; i < s.length; i++) units.push("0x" + s.charCodeAt(i).toString(16));
    return "@runtime.string_of_code_units([" + units.join(", ") + "])";
  }
  let out = "";
  for (const ch of s) {
    const cp = ch.codePointAt(0);
    if (ch === "\\") out += "\\\\";
    else if (ch === '"') out += '\\"';
    else if (ch === "\n") out += "\\n";
    else if (ch === "\r") out += "\\r";
    else if (ch === "\t") out += "\\t";
    else if (cp < 0x20 || cp >= 0x7f) out += "\\u{" + cp.toString(16) + "}";
    else out += ch;
  }
  return '"' + out + '"';
}

function mbtParts(parts) {
  return "[" + parts.map(p => Array.isArray(p)
    ? "Range(" + mbtString(p[0]) + ", " + mbtString(p[1]) + ")"
    : "Char(" + mbtString(p) + ")").join(", ") + "]";
}

function mbtExpectation(e) {
  switch (e.type) {
    case "rule": return "Other(description=" + mbtString(e.value) + ")";
    case "literal": return "Literal(text=" + mbtString(e.value) + ", ignore_case=" + e.ignoreCase + ")";
    case "class": return "Class(parts=" + mbtParts(e.value) + ", inverted=" + e.inverted + ", ignore_case=" + e.ignoreCase + ")";
    case "any": return "Any";
    default: throw new Error("unknown expectation " + JSON.stringify(e));
  }
}

function mbtIntArray(xs, indent) {
  const lines = [];
  for (let i = 0; i < xs.length; i += 16) lines.push(indent + "  " + xs.slice(i, i + 16).join(", ") + ",");
  return "[\n" + lines.join("\n") + "\n" + indent + "]";
}

function generate(grammarPath, name, options) {
  const source = fs.readFileSync(grammarPath, "utf8");
  const { ast } = compileInternals(source, options);
  const features = options.features || {};
  const use = f => (f in features ? !!features[f] : true);
  const i2 = "    ";
  const out = [];
  out.push("// Code generated by tools/gen-program.js from " + path.basename(grammarPath) + ". DO NOT EDIT.");
  out.push("");
  out.push("///|");
  out.push("let " + name + " : @bytecode.Program = {");
  out.push("  opcodes: @bytecode.default_opcodes,");
  out.push("  rules: [");
  for (const rule of ast.rules) {
    out.push("    { name: " + mbtString(rule.name) + ", bytecode: " + mbtIntArray(rule.bytecode, i2) + " },");
  }
  out.push("  ],");
  out.push("  literals: [" + ast.literals.map(mbtString).join(", ") + "],");
  out.push("  classes: [");
  for (const c of ast.classes) {
    out.push("    { parts: " + mbtParts(c.value) + ", inverted: " + c.inverted + ", ignore_case: " + c.ignoreCase + " },");
  }
  out.push("  ],");
  out.push("  expectations: [");
  for (const e of ast.expectations) out.push("    " + mbtExpectation(e) + ",");
  out.push("  ],");
  out.push("  functions: [");
  for (const f of ast.functions) {
    out.push("    { predicate: " + f.predicate + ", params: [" + f.params.map(mbtString).join(", ") + "], body: " + mbtString(f.body) + " },");
  }
  out.push("  ],");
  out.push("  initializer: " + (ast.initializer ? "Some(" + mbtString(ast.initializer.code) + ")" : "None") + ",");
  const start = options.allowedStartRules || [ast.rules[0].name];
  out.push("  allowed_start_rules: [" + start.map(mbtString).join(", ") + "],");
  out.push("  cache: " + !!options.cache + ",");
  out.push("  trace: " + !!options.trace + ",");
  out.push("  features: {");
  for (const [k, js] of [["text", "text"], ["offset", "offset"], ["range", "range"], ["location", "location"],
    ["expected", "expected"], ["error", "error"], ["filename", "filename"], ["default_tracer", "DefaultTracer"]]) {
    out.push("    " + k + ": " + use(js) + ",");
  }
  out.push("  },");
  out.push("}");
  return out.join("\n") + "\n";
}

module.exports = { generate, mbtString };

if (require.main === module) {
  const [grammarPath, name, opts] = process.argv.slice(2);
  process.stdout.write(generate(grammarPath, name, opts ? JSON.parse(opts) : {}));
}
