// Generates runtime/unicode_tables.mbt: the JavaScript case-mapping data
// that PEG.js generated parsers depend on, captured from the running engine.
//
//   node tools/gen-unicode.js > runtime/unicode_tables.mbt
//
// * LOWER_*: String.prototype.toLowerCase() for every code point whose
//   lowercase differs (context-free mapping; Final_Sigma handled separately).
// * CANON_*: ES RegExp Canonicalize() for non-unicode /i mode, per BMP code unit.
// * CASED / CASE_IGNORABLE: ranges used by the Final_Sigma rule.
"use strict";

const lowerKeys = [];
const lowerVals = [];
for (let cp = 0; cp <= 0x10ffff; cp++) {
  if (cp >= 0xd800 && cp <= 0xdfff) continue;
  const s = String.fromCodePoint(cp);
  const l = s.toLowerCase();
  if (l !== s) { lowerKeys.push(cp); lowerVals.push(l); }
}

function canonicalize(ch) {
  const s = String.fromCharCode(ch);
  const u = s.toUpperCase();
  if (u.length !== 1) return ch;
  const cu = u.charCodeAt(0);
  if (ch >= 128 && cu < 128) return ch;
  return cu;
}
const canonKeys = [];
const canonVals = [];
for (let c = 0; c <= 0xffff; c++) {
  const k = canonicalize(c);
  if (k !== c) { canonKeys.push(c); canonVals.push(k); }
}
// Cross-check the Canonicalize model against the engine's own regexps.
for (let i = 0; i < canonKeys.length; i++) {
  const a = String.fromCharCode(canonKeys[i]);
  const b = String.fromCharCode(canonVals[i]);
  const re = new RegExp("^[" + b.replace(/[\\\]^-]/g, "\\$&") + "]$", "i");
  if (!re.test(a)) throw new Error("canonicalize model mismatch at " + canonKeys[i].toString(16));
}

function ranges(re) {
  const out = [];
  let start = -1;
  for (let cp = 0; cp <= 0x110000; cp++) {
    const ok = cp <= 0x10ffff && re.test(String.fromCodePoint(cp));
    if (ok && start < 0) start = cp;
    if (!ok && start >= 0) { out.push(start, cp - 1); start = -1; }
  }
  return out;
}
const cased = ranges(/^\p{Cased}$/u);
const caseIgnorable = ranges(/^\p{Case_Ignorable}$/u);

function intArray(name, xs) {
  const lines = [];
  for (let i = 0; i < xs.length; i += 12) lines.push("  " + xs.slice(i, i + 12).join(", ") + ",");
  return "///|\nlet " + name + " : ReadOnlyArray[Int] = [\n" + lines.join("\n") + "\n]\n";
}
function esc(s) {
  let out = "";
  for (const ch of s) out += "\\u{" + ch.codePointAt(0).toString(16) + "}";
  return out;
}
function strArray(name, xs) {
  const lines = xs.map(s => '  "' + esc(s) + '",');
  return "///|\nlet " + name + " : ReadOnlyArray[String] = [\n" + lines.join("\n") + "\n]\n";
}

process.stdout.write(
  "// Code generated by tools/gen-unicode.js (node " + process.version +
  ", unicode " + process.versions.unicode + "). DO NOT EDIT.\n\n" +
  intArray("lower_keys", lowerKeys) + "\n" +
  strArray("lower_vals", lowerVals) + "\n" +
  intArray("canon_keys", canonKeys) + "\n" +
  intArray("canon_vals", canonVals) + "\n" +
  intArray("cased_ranges", cased) + "\n" +
  intArray("case_ignorable_ranges", caseIgnorable)
);
